spring:
  application:
    name: api-gateway
  cloud:
    config:
      enabled: false
    gateway:
      server:
        webmvc:
          routes:
            - id: product-service
              uri: http://localhost:8081
              predicates:
                - Path=/products/**
            - id: order-service
              uri: http://localhost:8082
              predicates:
                - Path=/orders/**
            - id: user-service
              uri: http://localhost:8083
              predicates:
                - Path=/auth/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8080
