CREATE TABLE products
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255),
    description    VARCHAR(255),
    price          DOUBLE PRECISION,
    stock_quantity INT,
    category       VARCHAR(255),
    image_url      VARCHAR(255),
    rating         VARCHAR(255),
    CONSTRAINT pk_products PRIMARY KEY (id)
);