spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:mem:user_db
    password:
    username: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  cloud:
    config:
      enabled: false

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

